application:
  port: 8000
  hosr: 0.0.0.0
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "whale"
  require_ssl: false
email_client:
  base_url: "https://localhost:8000"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000